### ISSUE TITLE
Move package to top level

### ISSUE THREAD

**Issue by 89z** [nagare-media/ingest#1]
Currently it seems the actual package is one level down:

https://godocs.io/github.com/nagare-media/ingest/pkg

it should be at the top level:

https://godocs.io/github.com/nagare-media/ingest

**Comment by mtneug** [comment]
The `pkg` package is a common convention for Go projects. As are the `cmd` and `internal` packages. Do you want to use something specific?

**Comment by mtneug** [comment]
I will close this. Feel free to comment if think this is still valid.

**Comment by 89z** [comment]
If you move the package to the top level, then the import path will be shorter
